import os
from PIL import Image, ImageDraw, ImageOps
import streamlit as st


def initialize_gui(director_name, with_sound):
    title = "[AISF](https://aisf.co/) Panel Simulation"
    st.set_page_config(
        initial_sidebar_state="expanded",
        page_title=title,
        layout="centered",
    )
    st.title(title)
    st.write(
        f"""Generate a fake panel discussion about any topic among fictitious renditions of
        [Hubert Thieblot](https://en.wikipedia.org/wiki/Hubert_Thieblot),
        [Edward Saatchi](https://en.wikipedia.org/wiki/Edward_Saatchi),
        [Jim Fan](https://jimfan.me/),
        [Joon Park](http://www.joonsungpark.com/),
        [Jack Soslow](https://twitter.com/JackSoslow), and
        [Michael Chang](https://mbchang.github.io/).
        {director_name} will moderate.
        """
    )

    st.sidebar.write(
        f"""
    # About

    The challenge faced by generating multi-agent simulations is determining the order in which the agents speak.
    To address this challenge, this application uses a "director" agent to decide the order in which the agents speak.
    You can find an example of how to implement this in the [LangChain docs](https://python.langchain.com/en/latest/use_cases/agent_simulations/multiagent_authoritarian.html).

    Created by [Michael Chang](https://mbchang.github.io/) ([@mmmbchang](https://twitter.com/mmmbchang)) at [LangChain](https://python.langchain.com/en/latest/).
    """
    )
    st.sidebar.write("---")
    openai_api_key = st.sidebar.text_input("Your OpenAI API KEY", type="password")
    os.environ["OPENAI_API_KEY"] = openai_api_key

    if with_sound:
        sound_on = st.sidebar.checkbox("Enable Sound")
        if sound_on:
            eleven_api_key = st.sidebar.text_input(
                "Your Eleven Labs API Key", type="password"
            )
            os.environ["ELEVEN_API_KEY"] = eleven_api_key
        else:
            st.sidebar.write("Sound is turned off.")

        debug_sound = st.sidebar.checkbox("Debug Sound")
    else:
        sound_on = False
        debug_sound = False

    termination_probability = st.sidebar.slider(
        label="Termination Probability",
        min_value=0.0,
        max_value=1.0,
        step=0.01,
        value=0.01,
    )

    openai_api_model = st.sidebar.selectbox(
        "Model name", options=["gpt-3.5-turbo", "gpt-4"]
    )

    st.sidebar.write("---")

    st.write("---")
    disclaimer_text = f"""
    # Disclaimer

    This application simulates a fake dialogue among fictitious renditions of real people.
    To protect the privacy of the individuals represented, note that:

    1. the content generated by this application is entirely synthetic and is not actual statements or opinions expressed by the individuals represented;
    2. the voices used in this application are synthetically generated by [Eleven Labs](https://eleven-labs.com/en/) and do not reflect the voices of the individuals represented.

    This application is intended for demonstration and entertainment purposes only.
    The creator of this application takes no responsibility for any actions taken based on its content.
    """
    st.sidebar.write(disclaimer_text)

    acknowledgements_text = f"""
    # Acknowledgements

    This application is powered by OpenAI and created with
    [LangChain](https://python.langchain.com/en/latest/),
    [Streamlit](https://streamlit.io/),
    and
    [Eleven Labs](https://beta.elevenlabs.io/).
    The UI design was inspired by [WhatIfGPT](https://github.com/realminchoi/whatifgpt).
    Thank you to the LangChain team for their support and feedback.
    """
    st.sidebar.write(acknowledgements_text)
    return sound_on, debug_sound, termination_probability, openai_api_model


def list_to_string(l):
    return ", ".join(l[:-1]) + ", and " + l[-1]


class Message:
    def __init__(self, name: str):
        self.name = name

        if self.name != "Audience member":
            icon_col, message_col = st.columns([1, 4], gap="medium")
            self.icon = self.get_icon(name)
            if name == "Hubert Thieblot":
                caption = f"{name}, Moderator"
            else:
                caption = f"{name}, Panelist"
            icon_col.image(self.icon, caption=caption)
            self.markdown = message_col.markdown

    def get_icon(self, name):
        if name == "Hubert Thieblot":
            icon_path = "images/hubert.jpg"
        elif name == "Edward Saatchi":
            icon_path = "images/edward.jpeg"
        elif name == "Jim Fan":
            icon_path = "images/jim.jpg"
        elif name == "Joon Park":
            icon_path = "images/joon.jpg"
        elif name == "Jack Soslow":
            icon_path = "images/jack.jpg"
        elif name == "Michael Chang":
            icon_path = "images/michael.jpg"
        else:
            raise ValueError(f"No picture for name: {name}")

        # Open the image file
        img = Image.open(icon_path)
        # Create a circular mask
        mask = Image.new("L", img.size, 0)
        mask_draw = ImageDraw.Draw(mask)
        mask_draw.ellipse((0, 0) + img.size, fill=255)
        # Apply the mask and save the result
        icon = ImageOps.fit(img, mask.size, centering=(0.5, 0.5))
        icon.putalpha(mask)

        return icon

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        pass

    def write(self, content):
        if self.name == "Audience member":
            st.markdown("*" + content + "*")  # Italicize the content
        else:
            self.markdown(content)
